/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import javax.swing.JOptionPane;

/**
 *
 * @author PaulaJCh
 */
public class FRM_Estudiantes extends javax.swing.JFrame {

    /**
     * Creates new form FRM_Estudiantes
     */
    public FRM_Estudiantes() {
        initComponents();
    }
    public void mostrarMensaje(String mensaje)
    {
        JOptionPane.showMessageDialog(null,mensaje);
    }
    public String[] devolverInformacion()
    {
        return this.gUI_RegistroEstudiantes2.devolverInformacion();
    }
    public String devolverCedula()
    {
        return this.gUI_RegistroEstudiantes2.devolverCedula();
    }
    
    public void mostrarInformacion(String arreglo[])
    {
        this.gUI_RegistroEstudiantes2.mostrarInformacion(arreglo);
    }
    
    // controles de bloqueos
    public void limpiarInterfaz()
    {
        this.gUI_RegistroEstudiantes2.limpiarInterfaz();
    }
    
    public void deshabilitarCedula()
    {
      this.gUI_RegistroEstudiantes2.deshabilitarCedula();
    }
    
    public void estadoInicial()
    {
        this.gUI_Botones1.estadoInicial();
        this.gUI_RegistroEstudiantes2.estadoInicial();
    }
    
    public void habilitarAgregar()
    {
        this.gUI_Botones1.habilitarAgregar();
        this.gUI_RegistroEstudiantes2.habilitarAgregar();
    }
    public void habilitarOpciones()
    {
        this.gUI_Botones1.habilitarOpciones();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gUI_Botones1 = new Vista.GUI_Botones();
        gUI_RegistroEstudiantes2 = new Vista.GUI_RegistroEstudiantes();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gUI_RegistroEstudiantes2, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(gUI_Botones1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(gUI_RegistroEstudiantes2, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(gUI_Botones1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Vista.GUI_Botones gUI_Botones1;
    private Vista.GUI_RegistroEstudiantes gUI_RegistroEstudiantes2;
    // End of variables declaration//GEN-END:variables
}
