/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Controlador_FRM_MenuPrincipal;

/**
 *
 * @author PaulaJCh
 */
public class FRM_MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FRM_MenuPrincipal
     */
    Controlador_FRM_MenuPrincipal controlador_FRM_MenuPrincipal;
    FRM_Estudiantes frm_Estudiantes;
    FRM_Cursos      frm_Cursos;
    FRM_Usuarios   frm_Usuarios;
    FRM_Matricula   fRM_Matricula;
    public FRM_MenuPrincipal() {
        initComponents();
        this.setLocation(100,100);//aparesca la ventana en ese lugar
        controlador_FRM_MenuPrincipal= new Controlador_FRM_MenuPrincipal();
        frm_Estudiantes = new FRM_Estudiantes();
        frm_Cursos= new FRM_Cursos();
        frm_Usuarios= new FRM_Usuarios();
        fRM_Matricula= new FRM_Matricula();
        agregarEventos();
        
    }
    
    public void agregarEventos(){
        this.jm_Salir.addActionListener(controlador_FRM_MenuPrincipal);
        this.jm_Estudiantes.addActionListener(controlador_FRM_MenuPrincipal);
        this.jm_Cursos.addActionListener(controlador_FRM_MenuPrincipal);
        this.jm_Matricula.addActionListener(controlador_FRM_MenuPrincipal);
        this.jm_Usuarios.addActionListener(controlador_FRM_MenuPrincipal);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem4 = new javax.swing.JCheckBoxMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        jm_Archivo = new javax.swing.JMenu();
        jm_Salir = new javax.swing.JCheckBoxMenuItem();
        jm_Mantenimientos = new javax.swing.JMenu();
        jm_Estudiantes = new javax.swing.JCheckBoxMenuItem();
        jm_Cursos = new javax.swing.JCheckBoxMenuItem();
        jm_Matricula = new javax.swing.JCheckBoxMenuItem();
        jm_Usuarios = new javax.swing.JCheckBoxMenuItem();

        jCheckBoxMenuItem4.setSelected(true);
        jCheckBoxMenuItem4.setText("jCheckBoxMenuItem4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jm_Archivo.setText("Archivo");

        jm_Salir.setSelected(true);
        jm_Salir.setText("Salir");
        jm_Archivo.add(jm_Salir);

        jMenuBar1.add(jm_Archivo);

        jm_Mantenimientos.setText("Mantenimientos");

        jm_Estudiantes.setSelected(true);
        jm_Estudiantes.setText("Estudiantes");
        jm_Mantenimientos.add(jm_Estudiantes);

        jm_Cursos.setSelected(true);
        jm_Cursos.setText("Cursos");
        jm_Mantenimientos.add(jm_Cursos);

        jm_Matricula.setSelected(true);
        jm_Matricula.setText("Matricula");
        jm_Mantenimientos.add(jm_Matricula);

        jm_Usuarios.setSelected(true);
        jm_Usuarios.setText("Usuarios");
        jm_Usuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jm_UsuariosActionPerformed(evt);
            }
        });
        jm_Mantenimientos.add(jm_Usuarios);

        jMenuBar1.add(jm_Mantenimientos);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jm_UsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jm_UsuariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jm_UsuariosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FRM_MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FRM_MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FRM_MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FRM_MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FRM_MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jm_Archivo;
    private javax.swing.JCheckBoxMenuItem jm_Cursos;
    private javax.swing.JCheckBoxMenuItem jm_Estudiantes;
    private javax.swing.JMenu jm_Mantenimientos;
    private javax.swing.JCheckBoxMenuItem jm_Matricula;
    private javax.swing.JCheckBoxMenuItem jm_Salir;
    private javax.swing.JCheckBoxMenuItem jm_Usuarios;
    // End of variables declaration//GEN-END:variables
}
