/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Controlador_FRM_Usuarios;
import javax.swing.JOptionPane;

/**
 *
 * @author PaulaJCh
 */
public class FRM_Usuarios extends javax.swing.JFrame {

    /**
     * Creates new form FRM_Usuarios
     */
 
   public FRM_Usuarios() {
        initComponents();
        this.setLocation(170,160);
        setVisible(false);
    }
   
    public void mostrarMensaje(String mensaje)
    {
        JOptionPane.showMessageDialog(null,mensaje);
    }

    public String[] devolverInformacion()
    {   
        return this.gUI_Usuarios1.devolverInformacion();
    }
    public String devolverUsuario()
    {   
        return this.gUI_Usuarios1.devolverUsuario();
    }
     public void mostrarInformacion(String arreglo[])
    {
        this.gUI_Usuarios1.mostrarInformacion(arreglo);
    }
      public void limpiarInterfaz()
    {
        this.gUI_Usuarios1.limpiarInterfaz();
    }
       public void deshabilitarUsuario()
    {
        this.gUI_Usuarios1.deshabilitarUsuario();
    }
       public void estadoInicial()
    {
       this.gUI_Usuarios1.estadoInicial();
       this.gUI_Botones1.estadoInicial();
    }
        public void habilitarAgregar()
   {
       this.gUI_Usuarios1.habilitarAgregar();
       this.gUI_Botones1.habilitarAgregar();
   }
        public void habilitarOpciones()
   {
       this.gUI_Botones1.habilitarOpciones();
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gUI_Usuarios1 = new Vista.GUI_RegistroUsuarios();
        gUI_Botones1 = new Vista.GUI_Botones();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(gUI_Usuarios1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(gUI_Botones1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(gUI_Usuarios1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(gUI_Botones1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Vista.GUI_Botones gUI_Botones1;
    private Vista.GUI_RegistroUsuarios gUI_Usuarios1;
    // End of variables declaration//GEN-END:variables
}
