/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import javax.swing.JOptionPane;

/**
 *
 * @author PaulaJCh
 */
public class FRM_Cursos extends javax.swing.JFrame {

    /**
     * Creates new form FRM_Cursos
     */
    public FRM_Cursos() {
         initComponents();
        this.setLocation(170,160);
        setVisible(false);
    }
   
    public void mostrarMensaje(String mensaje)
    {
        JOptionPane.showMessageDialog(null,mensaje);
    }

    public String[] devolverInformacion()
    {   
        return this.gUI_RegistroCursos1.devolverInformacion();
    }
    public String devolverSigla()
    {   
        return this.gUI_RegistroCursos1.devolverSigla();
    }
     public void mostrarInformacion(String arreglo[])
    {
        this.gUI_RegistroCursos1.mostrarInformacion(arreglo);
    }
        public void deshabilitarSigla()
    {
        this.gUI_RegistroCursos1.deshabilitarSigla();
    }
     
     // control 
      public void limpiarInterfaz()
    {
        this.gUI_RegistroCursos1.limpiarInterfaz();
    }
       public void estadoInicial()
    {
       this.gUI_RegistroCursos1.estadoInicial();
       this.gUI_Botones1.estadoInicial();
    }
        public void habilitarAgregar()
   {
       this.gUI_RegistroCursos1.habilitarAgregar();
       this.gUI_Botones1.habilitarAgregar();
   }
        public void habilitarOpciones()
   {
       this.gUI_Botones1.habilitarOpciones();
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gUI_RegistroCursos1 = new Vista.GUI_RegistroCursos();
        gUI_Botones1 = new Vista.GUI_Botones();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gUI_RegistroCursos1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gUI_Botones1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(gUI_RegistroCursos1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(gUI_Botones1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Vista.GUI_Botones gUI_Botones1;
    private Vista.GUI_RegistroCursos gUI_RegistroCursos1;
    // End of variables declaration//GEN-END:variables

  
}
