/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author PaulaJCh
 */
public class GUI_RegistroUsuarios extends javax.swing.JPanel {

    /**
     * Creates new form GUI_Usuarios
     */
     public GUI_RegistroUsuarios() {
        initComponents();
        cargarTipo();
    }
    public void cargarTipo()//COMBOBOX
    {
        this.jcb_Tipo.removeAllItems();
        
        for(int contador=0;contador<3;contador++){
            this.jcb_Tipo.addItem(""+contador);
        }
        this.jcb_Tipo.setSelectedIndex(1);
    }
    
     public String[] devolverInformacion()
    {
        String arreglo[];
        arreglo=new String[4];
        arreglo[0]=this.jt_NombreCompleto.getText();
        arreglo[1]=this.jt_Usuario.getText();
        arreglo[2]=this.jpf_Contrasena.getText();
        arreglo[3]=""+this.jcb_Tipo.getSelectedIndex();
         
        return arreglo;
    }
     public String devolverUsuario()
    {
        return jt_Usuario.getText();
    }
    
    public void mostrarInformacion(String arreglo[])
    {
        this.jt_NombreCompleto.setText(arreglo[0]);
        this.jpf_Contrasena.setText(arreglo[1]);
        this.jcb_Tipo.setSelectedIndex(Integer.parseInt(arreglo[2]));
    }
     public void limpiarInterfaz()
    {
        this.jt_NombreCompleto.setText("");
        this.jt_Usuario.setText("");
        this.jpf_Contrasena.setText("");
    }
     public void deshabilitarUsuario()
    {
        this.jt_NombreCompleto.setEnabled(true);
        this.jt_Usuario.setEnabled(false);
        this.jpf_Contrasena.setEnabled(true);
    }
    
    public void estadoInicial()
    {
       this.jt_NombreCompleto.setEnabled(false);
        this.jt_Usuario.setEnabled(true);
        this.jpf_Contrasena.setEnabled(false);
    }
    
    public void habilitarAgregar()
    {
        this.jt_NombreCompleto.setEnabled(true);
        this.jt_Usuario.setEnabled(true);
        this.jpf_Contrasena.setEnabled(true);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jl_NombreCompleto = new javax.swing.JLabel();
        jl_Usuario = new javax.swing.JLabel();
        jl_Contrasena = new javax.swing.JLabel();
        jl_Tipo = new javax.swing.JLabel();
        jt_NombreCompleto = new javax.swing.JTextField();
        jt_Usuario = new javax.swing.JTextField();
        jpf_Contrasena = new javax.swing.JPasswordField();
        jcb_Tipo = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();

        jl_NombreCompleto.setText("Nombre:");

        jl_Usuario.setText("Usuario:");

        jl_Contrasena.setText("Contraseña:");

        jl_Tipo.setText("Tipo:");

        jt_NombreCompleto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt_NombreCompletoActionPerformed(evt);
            }
        });

        jpf_Contrasena.setText("jPasswordField1");

        jcb_Tipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel5.setText("Registro de Usuarios");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jl_NombreCompleto)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jl_Contrasena)
                                    .addGap(30, 30, 30)
                                    .addComponent(jpf_Contrasena))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jl_Usuario)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(2, 2, 2)
                                            .addComponent(jl_Tipo)))
                                    .addGap(50, 50, 50)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jt_NombreCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jt_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jcb_Tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(jLabel5)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_NombreCompleto)
                    .addComponent(jt_NombreCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_Usuario)
                    .addComponent(jt_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_Contrasena)
                    .addComponent(jpf_Contrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcb_Tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_Tipo))
                .addContainerGap(25, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jt_NombreCompletoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt_NombreCompletoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jt_NombreCompletoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel5;
    private javax.swing.JComboBox jcb_Tipo;
    private javax.swing.JLabel jl_Contrasena;
    private javax.swing.JLabel jl_NombreCompleto;
    private javax.swing.JLabel jl_Tipo;
    private javax.swing.JLabel jl_Usuario;
    private javax.swing.JPasswordField jpf_Contrasena;
    private javax.swing.JTextField jt_NombreCompleto;
    private javax.swing.JTextField jt_Usuario;
    // End of variables declaration//GEN-END:variables
}
